version: '3.7'

services:
  frontend:
    container_name: makelead-front
    build: .
    command: 'yarn dev'
    environment:
      - HOST=0.0.0.0
      - WATCHPACK_POLLING=true
    ports:
      - "8080:8080" 
    volumes:
      - ./app:/app
    tty: true
    stdin_open: true
