version: "3.7"

services:
  frontend:
    container_name: find_front
    build: .
    command: "npm run dev"
    environment:
      - HOST=0.0.0.0
      - WATCHPACK_POLLING=true
    ports:
      - "8080:8080"
    volumes:
      - ./app:/app
      - /app/node_modules
    tty: true
    stdin_open: true
